name: wisdom-finance-backend
namespace: wisdom-finance
replicaCount: 2

image:
  repository: ghcr.io/ry-agent-03060383/wisdom-finance-backend
  tag: latest
  pullPolicy: Always

service:
  port: 80
  targetPort: 8080

env:
  SPRING_DATASOURCE_URL: "jdbc:mysql://mysql:3306/wf"
  SPRING_DATASOURCE_USERNAME: "root"
  SPRING_DATASOURCE_PASSWORD: "dbPwd"

probe:
  path: /actuator/health
  initialDelaySeconds: 20
  periodSeconds: 10
